config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :automated_tests

  resources :components

  root 'landings#index'

end

app/models/automated_test.rb
class AutomatedTest < ActiveRecord::Base
  belongs_to :component
  has_many :components
end

app/models/component.rb
class Component < ActiveRecord::Base
  belongs_to :automated_test
  has_many :automated_tests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/automated_tests_controller.rb
class AutomatedTestsController < ApplicationController
  before_action :set_automated_test, only: [:show, :edit, :update, :destroy]

  # GET /automated_tests
  # GET /automated_tests.json
  def index
    @automated_tests = AutomatedTest.all
  end

  # GET /automated_tests/1
  # GET /automated_tests/1.json
  def show
  end

  # GET /automated_tests/new
  def new
    @automated_test = AutomatedTest.new
  end

  # GET /automated_tests/1/edit
  def edit
  end

  # POST /automated_tests
  # POST /automated_tests.json
  def create
    @automated_test = AutomatedTest.new(automated_test_params)

    respond_to do |format|
      if @automated_test.save
        format.html { redirect_to @automated_test, notice: 'Automated test was successfully created.' }
        format.json { render :show, status: :created, location: @automated_test }
      else
        format.html { render :new }
        format.json { render json: @automated_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /automated_tests/1
  # PATCH/PUT /automated_tests/1.json
  def update
    respond_to do |format|
      if @automated_test.update(automated_test_params)
        format.html { redirect_to @automated_test, notice: 'Automated test was successfully updated.' }
        format.json { render :show, status: :ok, location: @automated_test }
      else
        format.html { render :edit }
        format.json { render json: @automated_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /automated_tests/1
  # DELETE /automated_tests/1.json
  def destroy
    @automated_test.destroy
    respond_to do |format|
      format.html { redirect_to automated_tests_url, notice: 'Automated test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_automated_test
      @automated_test = AutomatedTest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def automated_test_params
      params.require(:automated_test).permit(:title, :type, :description, :component_id)
    end
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  before_action :set_component, only: [:show, :edit, :update, :destroy]

  # GET /components
  # GET /components.json
  def index
    @components = Component.all
  end

  # GET /components/1
  # GET /components/1.json
  def show
  end

  # GET /components/new
  def new
    @component = Component.new
  end

  # GET /components/1/edit
  def edit
  end

  # POST /components
  # POST /components.json
  def create
    @component = Component.new(component_params)

    respond_to do |format|
      if @component.save
        format.html { redirect_to @component, notice: 'Component was successfully created.' }
        format.json { render :show, status: :created, location: @component }
      else
        format.html { render :new }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /components/1
  # PATCH/PUT /components/1.json
  def update
    respond_to do |format|
      if @component.update(component_params)
        format.html { redirect_to @component, notice: 'Component was successfully updated.' }
        format.json { render :show, status: :ok, location: @component }
      else
        format.html { render :edit }
        format.json { render json: @component.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /components/1
  # DELETE /components/1.json
  def destroy
    @component.destroy
    respond_to do |format|
      format.html { redirect_to components_url, notice: 'Component was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_component
      @component = Component.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def component_params
      params.require(:component).permit(:name, :type, :description, :automated_test_id)
    end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/automated_tests_helper.rb
module AutomatedTestsHelper
end

app/helpers/components_helper.rb
module ComponentsHelper
end

app/helpers/landings_helper.rb
module LandingsHelper
end

app/views/automated_tests/_form.html.erb
<%= form_for @automated_test, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  automated_tests_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/automated_tests/edit.html.erb
<%- model_class = AutomatedTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => AutomatedTest %></h1>
</div>
<%= render :partial => 'form' %>

app/views/automated_tests/index.html.erb
<%- model_class = AutomatedTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => AutomatedTest %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @automated_tests.each do |automated_test| %>
      <tr>
        <td><%= automated_test.id %></td>
        <td><%= automated_test.title %></td>
        <td><%= automated_test.type %></td>
        <td><%= automated_test.description %></td>
        <td><%=l automated_test.created_at, format: :long %></td>
        <td>
          <%= link_to automated_test_path(automated_test), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to automated_test_path(automated_test), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_automated_test_path,
            :class => 'btn btn-primary' %>

app/views/automated_tests/new.html.erb
<%- model_class = AutomatedTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => AutomatedTest %></h1>
</div>
<%= render :partial => 'form' %>

app/views/automated_tests/show.html.erb
<%- model_class = AutomatedTest -%>
<div class="page-header">
  <h1><%=t '.title', :default => AutomatedTest %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @automated_test.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:type) %></dt>
      <dd><pre class="prettyprint"><%= @automated_test.type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @automated_test.description %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              automated_tests_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_automated_test_path(@automated_test), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              automated_test_path(@automated_test),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "My Application", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/landings/index.html.erb
<h1>Landings#index</h1>
<p>Find me in app/views/landings/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teamwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>